name: free_english_dictionary
description: Dart package that provides English dictionary meaning for word.
version: 0.0.1+1
homepage: https://github.com/haybankz/free_english_dictionary/blob/main/README.md
repository: https://github.com/haybankz/free_english_dictionary

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  dio: ^5.3.3
  dio_cache_interceptor: ^3.4.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
