name: free_dictionary
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/haybankz/free_dictionary/blob/main/README.md
repository: https://github.com/haybankz/free_dictionary

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  dio: ^5.3.3
  dio_cache_interceptor: ^3.4.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
